version: "3.9"

services:
  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    environment:
      PORT: 3000
      API_PREFIX: /api/v1
      AUTH_SERVICE_URL: http://auth-service:3001
      USER_SERVICE_URL: http://user-service:3002
      PRODUCT_SERVICE_URL: http://product-service:3003
      ORDER_SERVICE_URL: http://order-service:3004
      STORE_SERVICE_URL: http://store-service:3005
      CONTENT_SERVICE_URL: http://content-service:3006
      CONFIG_SERVICE_URL: http://config-service:3007
      SHIPPING_SERVICE_URL: http://shipping-service:3008
      ERP_SERVICE_URL: http://erp-service:3009
      UTILITY_SERVICE_URL: http://utility-service:3010
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=bloom"
      - "traefik.http.routers.api-gateway.rule=Host(`${BACKEND_DOMAIN}`)"
      - "traefik.http.routers.api-gateway.entrypoints=websecure"
      - "traefik.http.routers.api-gateway.tls.certresolver=myresolver"
      - "traefik.http.routers.api-gateway.service=api-gateway"
      - "traefik.http.services.api-gateway.loadbalancer.server.port=3000"
    expose:
      - "3000"
    networks:
      - bloom

  auth-service:
    container_name: auth-service
    build: ./auth-service
    environment:
      PORT: 3001
    env_file: .env
    expose:
      - "3001"
    depends_on:
      - api-gateway
    networks:
      - bloom

  user-service:
    container_name: user-service
    build: ./user-service
    environment:
      PORT: 3002
    env_file: .env
    expose:
      - "3002"
    depends_on:
      - auth-service
    networks:
      - bloom

  product-service:
    container_name: product-service
    build: ./product-service
    environment:
      PORT: 3003
    env_file: .env
    expose:
      - "3003"
    depends_on:
      - user-service
    networks:
      - bloom

  order-service:
    container_name: order-service
    build: ./order-service
    environment:
      PORT: 3004
    env_file: .env
    expose:
      - "3004"
    depends_on:
      - product-service
    networks:
      - bloom

  store-service:
    container_name: store-service
    build: ./store-service
    environment:
      PORT: 3005
    env_file: .env
    expose:
      - "3005"
    depends_on:
      - order-service
    networks:
      - bloom

  content-service:
    container_name: content-service
    build: ./content-service
    environment:
      PORT: 3006
    env_file: .env
    expose:
      - "3006"
    depends_on:
      - store-service
    networks:
      - bloom

  config-service:
    container_name: config-service
    build: ./config-service
    environment:
      PORT: 3007
    env_file: .env
    expose:
      - "3007"
    depends_on:
      - content-service
    networks:
      - bloom

  shipping-service:
    container_name: shipping-service
    build: ./shipping-service
    environment:
      PORT: 3008
    env_file: .env
    expose:
      - "3008"
    depends_on:
      - config-service
    networks:
      - bloom

  erp-service:
    container_name: erp-service
    build: ./erp-service
    environment:
      PORT: 3009
    env_file: .env
    expose:
      - "3009"
    depends_on:
      - shipping-service
    networks:
      - bloom

  utility-service:
    container_name: utility-service
    build: ./utility-service
    environment:
      PORT: 3010
    env_file: .env
    expose:
      - "3010"
    depends_on:
      - erp-service
    networks:
      - bloom

networks:
  bloom:
    external: true
