import env from "../config/env";

export default {
  CURRENY_SYMBOL: "₹",
  CURRENY_CODE: "&#8377;",
  NODE_ENV: env.env,
  businessEmail: env.businessEmail,
  CLIENT_URL: env.CLIENT_URL,
  JWT_BUILDER_TOKEN: env.JWT_BUILDER_TOKEN,
  websiteUrl: env.websiteUrl,
  BACKEND_API_URL: env.BACKEND_API_URL,
  STARTER_PLAN_ID: "Starter",
  // STARTER_PLAN_ID: "85f23124-caf6-4d12-a5c4-8f0b257faa15",
  AUTH_TOKEN: "AUTH_TOKEN",
  AUTH_SERVICE: "/?serviceDomain=authService",
  CHECK_SUBDOMAIN_SERVICE: "/?serviceDomain=checkSubDomain",
  CART_SERVICE: "/?serviceDomain=cartService",
  CUSTOMER_SERVICE: "/?serviceDomain=customerService",
  IMAGE_SERVICE: "/?serviceDomain=imageserviceService",
  ORDER_SERVICE: "/?serviceDomain=orderService",
  PRODUCT_SERVICE: "/?serviceDomain=productService",
  SITE_CONFIG_SERVICE: "/?serviceDomain=siteconfigService",
  STORE_SERVICE: "/?serviceDomain=storeService",
  RESTAURANT_SERVICE: "/?serviceDomain=restaurantService",
  COMMON_SERVICE: "/?serviceDomain=ecomService",
  CREATE_SITE_SERVICE: "/?serviceDomain=createSite",
  EMAIL_SERVICE: "https://dev-bloom-email-service.azurewebsites.net",
  SOURCE_TYPE: "portal",
  SELECTED_STORE_ID: "SELECTED_STORE_ID",
};
